### ISSUE TITLE
Crawler endpoint returns inconsistent data

### ISSUE THREAD

**Issue by lhannest** [biothings/biothings_explorer_jsonld#11]
This endpoint is returning very odd data:
http://biothings.io/explorer/api/v2/crawler?input_type=mondo&input_value=0018911

```
{
    "linkedData": {
        "disease": [
            {
                "prefix": "MONDO",
                "object": {
                    "id": "MONDO:0007669",
                    "secondary-id": "HGNC.SYMBOL:renal cysts and diabetes syndrome"
                },
                "predicate": "DiseaseToGeneOrGeneProductAssociation",
                "api": "BioLink API",
                "edge": {
                    "label": "has phenotype",
                    "provided_by": "orphanet.ttl",
                    "id": "RO:0002200"
                }
            },
    ...
    ],
    ...
}
```
The predicate, edge label, and object ID seem to contradict each other. This is a disease to disease relationship (MONDO:0018911 --> MONDO:0007669), not a disease to phenotype (unless a disease counts as a phenotype?) or disease to gene relationship.

**Comment by kevinxin90** [comment]
@lhannest Hi Lance, thanks very much for reporting that! I just figured out it's because the BioLink API recently changed their output structure for one of their endpoints. And the JSON-LD file we provided for BioLink didn't catch up with that. That's the reason causing the error. It's currently fixed. Please try again! And we will also build better test modules to monitor the integrated APIs. Thanks again!

**Comment by lhannest** [comment]
Thanks for the quick fix, @kevinxin90 !
